name: Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 저장소 코드 가져오기

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        # Jekyll로 빌드 진행 (_site 폴더에 결과물 생성)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./_site
        # 빌드된 `_site` 폴더를 아티팩트로 저장

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
        # GitHub Pages에 배포
