name: Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 코드 체크아웃

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        # Jekyll을 사용하여 페이지 빌드

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./_site
        # 빌드된 사이트 아티팩트 업로드

    post:
      - name: Post job cleanup
        run: |
          git version
          # 기타 정리 작업 수행